### ISSUE TITLE
unknown option 'required' for configuration parameter: key

### ISSUE THREAD

**Issue by ajthenewguy** [fluent-plugins-nursery/fluent-plugin-concat#29]
```
<filter App1.*>
  @type concat
  key log
  stream_identity_key container_id
  multiline_start_regexp /^App1/
  multiline_end_regexp /^App1/
</filter>
```
Log lines from the application start with "App1 - ".
Starting up fluent (via docker-compose) results in the following error:

```
fluentd          | 2017-02-01 23:59:37 +0000 [error]: #0 unexpected error error_class=ArgumentError error="unknown option 'required' for configuration parameter: key"
fluentd          |   2017-02-01 23:59:37 +0000 [error]: #0 /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.12/lib/fluent/config/configure_proxy.rb:244:in `block in config_parameter_option_validate!'
fluentd          |   2017-02-01 23:59:37 +0000 [error]: #0 /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.12/lib/fluent/config/configure_proxy.rb:233:in `each_key'
fluentd          |   2017-02-01 23:59:37 +0000 [error]: #0 /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.12/lib/fluent/config/configure_proxy.rb:233:in `config_parameter_option_validate!'
fluentd          |   2017-02-01 23:59:37 +0000 [error]: #0 /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.12/lib/fluent/config/configure_proxy.rb:250:in `parameter_configuration'
```

I don't expect those errors, but rather an instance that will parse my multiple entries into a single entry, provided each entry begins with "App1 -".

**Comment by okkez** [comment]
Use v2.0.1 please.
I've just released new version.
