### ISSUE TITLE
emit transaction failed: error_class=NoMethodError error="undefined method `key?' for \"\":String"

### ISSUE THREAD

**Issue by victortrac** [fluent-plugins-nursery/fluent-plugin-concat#92]
#### Problem
We're using fluentd with this sqs input plugin: https://github.com/ixixi/fluent-plugin-sqs/blob/master/lib/fluent/plugin/in_sqs.rb

The output from the in_sqs.rb is a simple hashmap that gets sent to `router.emit(@tag, Fluent::Engine.now, record)`.

This used to work fine, but with some recent update, we're seeing this error:

```
2020-09-08 20:13:54 +0000 [warn]: emit transaction failed: error_class=NoMethodError error="undefined method `key?' for \"\":String" location="/usr/local/bundle/gems/fluent-plugin-concat-2.4.0/lib/fluent/plugin/filter_concat.rb:122:in `block in filter_stream'" tag="sqs.events"
2020-09-08 20:13:54.952415041 +0000 fluent.warn: {"error":"#<NoMethodError: undefined method `key?' for \"\":String>","location":"/usr/local/bundle/gems/fluent-plugin-concat-2.4.0/lib/fluent/plugin/filter_concat.rb:122:in `block in filter_stream'","tag":"sqs.events","message":"emit transaction failed: error_class=NoMethodError error=\"undefined method `key?' for \\\"\\\":String\" location=\"/usr/local/bundle/gems/fluent-plugin-concat-2.4.0/lib/fluent/plugin/filter_concat.rb:122:in `block in filter_stream'\" tag=\"sqs.events\""}
  2020-09-08 20:13:54 +0000 [warn]: /usr/local/bundle/gems/fluent-plugin-concat-2.4.0/lib/fluent/plugin/filter_concat.rb:122:in `block in filter_stream'
  2020-09-08 20:13:54 +0000 [warn]: /usr/local/bundle/gems/fluentd-1.11.2/lib/fluent/event.rb:110:in `each'
  2020-09-08 20:13:54 +0000 [warn]: /usr/local/bundle/gems/fluent-plugin-concat-2.4.0/lib/fluent/plugin/filter_concat.rb:117:in `filter_stream'
  2020-09-08 20:13:54 +0000 [warn]: /usr/local/bundle/gems/fluentd-1.11.2/lib/fluent/event_router.rb:178:in `block in filter_stream'
  2020-09-08 20:13:54 +0000 [warn]: /usr/local/bundle/gems/fluentd-1.11.2/lib/fluent/event_router.rb:178:in `each'
  2020-09-08 20:13:54 +0000 [warn]: /usr/local/bundle/gems/fluentd-1.11.2/lib/fluent/event_router.rb:178:in `reduce'
  2020-09-08 20:13:54 +0000 [warn]: /usr/local/bundle/gems/fluentd-1.11.2/lib/fluent/event_router.rb:178:in `filter_stream'
  2020-09-08 20:13:54 +0000 [warn]: /usr/local/bundle/gems/fluentd-1.11.2/lib/fluent/event_router.rb:159:in `emit_events'
  2020-09-08 20:13:54 +0000 [warn]: /usr/local/bundle/gems/fluentd-1.11.2/lib/fluent/event_router.rb:97:in `emit_stream'
  2020-09-08 20:13:54 +0000 [warn]: /usr/local/bundle/gems/fluentd-1.11.2/lib/fluent/event_router.rb:88:in `emit'
  2020-09-08 20:13:54 +0000 [warn]: /usr/local/bundle/gems/fluent-plugin-sqs-3.0.0/lib/fluent/plugin/in_sqs.rb:58:in `block in run'
  2020-09-08 20:13:54 +0000 [warn]: /usr/local/bundle/gems/aws-sdk-core-3.105.0/lib/aws-sdk-core/resources/collection.rb:54:in `yield'
  2020-09-08 20:13:54 +0000 [warn]: /usr/local/bundle/gems/aws-sdk-core-3.105.0/lib/aws-sdk-core/resources/collection.rb:54:in `block (3 levels) in each'
  2020-09-08 20:13:54 +0000 [warn]: /usr/local/bundle/gems/aws-sdk-core-3.105.0/lib/aws-sdk-core/resources/collection.rb:53:in `each'
  2020-09-08 20:13:54 +0000 [warn]: /usr/local/bundle/gems/aws-sdk-core-3.105.0/lib/aws-sdk-core/resources/collection.rb:53:in `block (2 levels) in each'
  2020-09-08 20:13:54 +0000 [warn]: /usr/local/bundle/gems/aws-sdk-core-3.105.0/lib/aws-sdk-core/resources/collection.rb:102:in `yield'
  2020-09-08 20:13:54 +0000 [warn]: /usr/local/bundle/gems/aws-sdk-core-3.105.0/lib/aws-sdk-core/resources/collection.rb:102:in `block (2 levels) in non_empty_batches'
  2020-09-08 20:13:54 +0000 [warn]: /usr/local/bundle/gems/aws-sdk-core-3.105.0/lib/aws-sdk-core/resources/collection.rb:101:in `each'
  2020-09-08 20:13:54 +0000 [warn]: /usr/local/bundle/gems/aws-sdk-core-3.105.0/lib/aws-sdk-core/resources/collection.rb:101:in `block in non_empty_batches'
  2020-09-08 20:13:54 +0000 [warn]: /usr/local/bundle/gems/aws-sdk-core-3.105.0/lib/aws-sdk-core/resources/collection.rb:52:in `each'
  2020-09-08 20:13:54 +0000 [warn]: /usr/local/bundle/gems/aws-sdk-core-3.105.0/lib/aws-sdk-core/resources/collection.rb:52:in `each'
  2020-09-08 20:13:54 +0000 [warn]: /usr/local/bundle/gems/aws-sdk-core-3.105.0/lib/aws-sdk-core/resources/collection.rb:52:in `block in each'
  2020-09-08 20:13:54 +0000 [warn]: /usr/local/bundle/gems/aws-sdk-core-3.105.0/lib/aws-sdk-core/resources/collection.rb:58:in `each'
  2020-09-08 20:13:54 +0000 [warn]: /usr/local/bundle/gems/aws-sdk-core-3.105.0/lib/aws-sdk-core/resources/collection.rb:58:in `each'
  2020-09-08 20:13:54 +0000 [warn]: /usr/local/bundle/gems/aws-sdk-core-3.105.0/lib/aws-sdk-core/resources/collection.rb:58:in `each'
  2020-09-08 20:13:54 +0000 [warn]: /usr/local/bundle/gems/fluent-plugin-sqs-3.0.0/lib/fluent/plugin/in_sqs.rb:56:in `run'
  2020-09-08 20:13:54 +0000 [warn]: /usr/local/bundle/gems/fluentd-1.11.2/lib/fluent/plugin_helper/timer.rb:80:in `on_timer'
  2020-09-08 20:13:54 +0000 [warn]: /usr/local/bundle/gems/cool.io-1.6.0/lib/cool.io/loop.rb:88:in `run_once'
  2020-09-08 20:13:54 +0000 [warn]: /usr/local/bundle/gems/cool.io-1.6.0/lib/cool.io/loop.rb:88:in `run'
  2020-09-08 20:13:54 +0000 [warn]: /usr/local/bundle/gems/fluentd-1.11.2/lib/fluent/plugin_helper/event_loop.rb:93:in `block in start'
  2020-09-08 20:13:54 +0000 [warn]: /usr/local/bundle/gems/fluentd-1.11.2/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
2020-09-08 20:13:54 +0000 [error]: failed to emit or receive error="undefined method `key?' for \"\":String" error_class="NoMethodError"
```

#### Your environment

We're simply using this docker image:
quay.io/fluentd_elasticsearch/fluentd:v3.0.2

fluentd --version
fluentd 1.11.2

```fluent-gem list

*** LOCAL GEMS ***

activesupport (6.0.3.2, 6.0.3.1)
addressable (2.7.0)
aws-eventstream (1.1.0)
aws-partitions (1.365.0)
aws-sdk-core (3.105.0)
aws-sdk-sqs (1.32.0)
aws-sigv4 (1.2.2)
benchmark (default: 0.1.0)
bigdecimal (default: 2.0.0)
bundler (default: 2.1.4)
cgi (default: 0.1.0)
concurrent-ruby (1.1.7, 1.1.6)
cool.io (1.6.0)
csv (3.1.7, default: 3.1.2)
date (3.0.1, default: 3.0.0)
dbm (default: 1.1.0)
delegate (default: 0.1.0)
did_you_mean (default: 1.4.0)
domain_name (0.5.20190701)
elasticsearch (7.9.0, 7.7.0)
elasticsearch-api (7.9.0, 7.7.0)
elasticsearch-transport (7.9.0, 7.7.0)
etc (default: 1.1.0)
excon (0.76.0, 0.73.0)
faraday (1.0.1)
fcntl (default: 1.0.0)
ffi (1.13.1, 1.12.2)
ffi-compiler (1.0.1)
fiddle (default: 1.0.0)
fileutils (default: 1.4.1)
fluent-plugin-concat (2.4.0)
fluent-plugin-detect-exceptions (0.0.13)
fluent-plugin-elasticsearch (4.1.2, 4.0.9)
fluent-plugin-kubernetes_metadata_filter (2.5.2, 2.4.6)
fluent-plugin-multi-format-parser (1.0.0)
fluent-plugin-prometheus (1.8.3, 1.8.0)
fluent-plugin-sqs (3.0.0)
fluent-plugin-systemd (1.0.2)
fluentd (1.11.2, 1.9.3)
forwardable (default: 1.3.1)
gdbm (default: 2.1.0)
getoptlong (default: 0.1.0)
http (4.4.1)
http-accept (2.1.1, 1.7.0)
http-cookie (1.0.3)
http-form_data (2.3.0)
http-parser (1.2.1)
http_parser.rb (0.6.0)
i18n (1.8.5, 1.8.2)
io-console (default: 0.5.6)
ipaddr (default: 1.2.2)
irb (1.2.4, default: 1.2.3)
jmespath (1.4.0)
json (2.3.1, default: 2.3.0)
jsonpath (1.0.5)
kubeclient (4.9.1, 4.6.0)
logger (default: 1.4.2)
lru_redux (1.1.0)
matrix (0.3.0, default: 0.2.0)
mime-types (3.3.1)
mime-types-data (3.2020.0512)
minitest (5.14.2, 5.14.1, 5.13.0)
msgpack (1.3.3)
multi_json (1.15.0, 1.14.1)
multipart-post (2.1.1)
mutex_m (default: 0.1.0)
net-pop (default: 0.1.0)
net-smtp (default: 0.1.0)
net-telnet (0.2.0)
netrc (0.11.0)
observer (default: 0.1.0)
oj (3.10.14, 3.10.6)
open3 (default: 0.1.0)
openssl (2.2.0, default: 2.1.2)
ostruct (default: 0.2.0)
power_assert (1.2.0, 1.1.7)
prime (default: 0.1.1)
prometheus-client (2.1.0, 0.9.0)
pstore (default: 0.1.0)
psych (3.2.0, default: 3.1.0)
public_suffix (4.0.6, 4.0.5)
quantile (0.2.1)
racc (1.5.0, default: 1.4.16)
rake (13.0.1)
rdoc (default: 6.2.1)
readline (default: 0.0.2)
readline-ext (default: 0.1.0)
recursive-open-struct (1.1.2, 1.1.1)
reline (0.1.4, default: 0.1.3)
rest-client (2.1.0)
rexml (3.2.4, default: 3.2.3)
rss (0.2.9, default: 0.2.8)
sdbm (default: 1.0.0)
serverengine (2.2.1)
sigdump (0.2.4)
singleton (default: 0.1.0)
stringio (0.1.4, default: 0.1.0)
strptime (0.2.4)
strscan (default: 1.0.3)
systemd-journal (1.3.3)
test-unit (3.3.6, 3.3.4)
thread_safe (0.3.6)
timeout (default: 0.1.0)
to_regexp (0.2.1)
tracer (default: 0.1.0)
tzinfo (2.0.2, 1.2.7)
tzinfo-data (1.2020.1)
unf (0.1.4)
unf_ext (0.0.7.7)
uri (default: 0.10.0)
webrick (default: 1.6.0)
xmlrpc (0.3.0)
yajl-ruby (1.4.1)
yaml (default: 0.1.0)
zeitwerk (2.4.0, 2.3.0)
zlib (default: 1.1.0)```

**Comment by victortrac** [comment]
Seems like this is user error. We had changed the in_sqs plugin without emitting a "body" field on record hash.
